config/routes.rb
Rails.application.routes.draw do
  get 'home/new'
  post 'home/create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_form, only: :create
  before_action :validate_form, only: :create
  before_action :validate_api, only: :create

  def new
    @create_form = CreateForm.new
  end

  def create
    create_by_api!(@create_form.code)
    flash[:messages] = ['登録できました']
    redirect_to home_new_path
  rescue StandardError
    flash[:messages] = ['登録に失敗しました']
    redirect_to home_new_path
  end

  private

  def create_params
    params.require(:create_form).permit(:code)
  end

  def valid_by_api?(code)
    # 外部APIを使った確認：常にTrueを返す
    true
  end

  def create_by_api!(code)
    # 外部APIを使った登録：常にTrueを返す
    true
  end

  def set_form
    @create_form = CreateForm.new(create_params)
  end

  def validate_form
    return if @create_form.valid?

    flash[:messages] = @create_form.errors.map(&:full_message)
    redirect_to home_new_path
  end

  def validate_api
    return if valid_by_api?(@create_form.code)

    flash[:messages] = ['バリデーションエラーとなりました']
    redirect_to home_new_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/create.html.erb
<h1>Home#create</h1>
<p>Find me in app/views/home/create.html.erb</p>

app/views/home/new.html.erb
<h1>登録フォーム</h1>
<%= form_with(model: @create_form, url: home_create_path, method: :post, local: true) do |f| %>
  <% flash[:messages]&.each do |message| %>
    <div><%= message %></div>
  <% end %>

  <div class="field">
    <%= f.label :code, 'Code' %>
    <%= f.text_field :code, autofocus: true %>
  </div>

  <div class="actions">
    <%= f.submit '送信' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ControllerFilterApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>